### Error Handling

Whenever you run a program that has errors, you may have noticed that Replit attempts to tells you what kind of error it is. 

For example, if you try to divide by zero, you get a message in the console saying that there was an error called `ZeroDivisionError`.

![](https://raw.githubusercontent.com/MissStrong/ICS3UE_Semester_2_2020-2021/main/Images/Zero_Division_Error.png)

An **error** or **exception** is a problem that occurs while a program is running. When an error occurs in Python, we say that program **raises** an error. When this happens and your program doesn't **handle** it, the program terminates abruptly. We can handle errors using a `try`-`except` structure.

Here is an example of a function that handles a division by zero error.

```python
def divide_three_ints(a, b, c):
  try:
    return a/b/c
  except:
    if b == 0:
      print("Error. B cannot be zero.")
    if c == 0:
      print("Error. C cannot be zero.")
```

The content in the `try` block is run first. The program tries to run the lines in the block; if an error is raised and the rest of the block does not run. 

The content in the `except` block runs only when an errror such as `ZeroDivisionError` has been raised. It "catches" the error and prevents the program from abruptly terminating and giving you a red error message.

If we want an `except` block to catch only a specific type of error, we can do that like this:

```python
def divide_three_ints(a, b, c):
  try:
    return a/b/c
  except ZeroDivisionError:  # This block runs when there is an error raised due to dividing by zero
    if b == 0:
      print("Error. B cannot be zero.")
    if c == 0:
      print("Error. C cannot be zero.")
  except:  # This block runs when a different error is raised
    print("Something else went wrong.")
```

When we are opening a file to read it and we want to make sure the program  doesn't crash when the filepath does not exist, we can call `open()` in a `try` block and catch the `FileNotFoundError` in an `except` block. 

```python
try:
  with open(filepath, "r") as f:
    print(f.read())
except FileNotFoundError:
  print("That file does not exist.")
```
